/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airplane;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JTextArea;

/**
 *
 * @author Martin LEGRIS
 * @author Sacha MASSON
 */
/**
 * Generates the Swing View
 */
public final class View extends javax.swing.JFrame implements ActionListener {

    private Handle manette = new Handle();
    private Software soft = new Software();
    private JTextArea textArea;

    /**
     *
     */
    public View() {
        initComponents();
        jRadioButton1.setEnabled(false);
        jRadioButton2.setEnabled(false);
        jRadioButton3.setEnabled(false);
        jRadioButton4.setEnabled(false);
        jButton1.setEnabled(false);
        jButton2.setEnabled(true);
        
        //on initialise les voyants à éteint
        moveLights(LightsEnum.ETEINT);
    }

    /**
     *
     * @param s
     */
    public void log(String s) {
        textArea.append(s);
    }

    //Gestion des voyants

    /**
     *
     * @param couleur
     */
        public void moveLights(LightsEnum couleur) {
        if (couleur == LightsEnum.ORANGE) {
            jRadioButton1.setSelected(false);
            jRadioButton2.setSelected(true);
            jRadioButton3.setSelected(false);
            jRadioButton4.setSelected(false);
        }

        if (couleur == LightsEnum.ROUGE) {
            jRadioButton1.setSelected(true);
            jRadioButton2.setSelected(false);
            jRadioButton3.setSelected(false);
            jRadioButton4.setSelected(false);
        }

        if (couleur == LightsEnum.VERT) {
            jRadioButton1.setSelected(false);
            jRadioButton2.setSelected(false);
            jRadioButton3.setSelected(true);
            jRadioButton4.setSelected(false);
        }

        if (couleur == LightsEnum.ETEINT) {
            jRadioButton1.setSelected(false);
            jRadioButton2.setSelected(false);
            jRadioButton3.setSelected(false);
            jRadioButton4.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        javax.swing.JLabel jLabel1;
        javax.swing.JLabel jLabel2;
        textArea = new JTextArea(10, 20);
        textArea.setEditable(false);
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        textArea.setAutoscrolls(true);

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();

        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Up");
        jButton1.addActionListener(this);
        jButton2.addActionListener(this);

        jButton2.setText("Down");

        jRadioButton1.setText("Rouge - Panne");
        jRadioButton2.setText("Orange - En mouvement");
        jRadioButton3.setText("Vert - Train d'atterissage sorti");
        jRadioButton4.setText("Eteint - Train rentré");
        jLabel1.setText("Manette");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jRadioButton4)
                                                .addComponent(jRadioButton2)
                                                .addComponent(jRadioButton3)
                                                .addComponent(jRadioButton1)))
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(117, 117, 117)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2))
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(173, 173, 173)
                                        .addComponent(jLabel1))
                                .addGap(173, 173, 173)
                                .addComponent(textArea))
                        .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1)
                                .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton4)
                        .addGap(3, 3, 3)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addGap(30, 30, 30)
                        .addComponent(textArea)
                        .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;

    // End of variables declaration
    @Override
    public void actionPerformed(ActionEvent e) {
        Object source = e.getSource();

        //Handle UP
        if (source.equals(jButton2)) {
            manette.setPosition(HandleEnum.BAS);
            textArea.append("Début de la séquence d'atterissage\n");
            //Simulation de la manette : quand elle est en position basse on ne peut plus appuyer sur down et inversement
            jButton2.setEnabled(false);
            jButton1.setEnabled(true);
            soft.doSoft(manette, this);

            //Handle Down
        } else if (source.equals(jButton1)) {
            manette.setPosition(HandleEnum.HAUT);
            textArea.append("Début de la séquence de décollage\n");
            //Simulation de la manette : quand elle est en position basse on ne peut plus appuyer sur down et inversement
            jButton1.setEnabled(false);
            jButton2.setEnabled(true);
            soft.doSoft(manette, this);

        }
    }
}
